add_newline = true
#format = "[](bold black)[$git_branch$directory](bold bg:black fg:white) "
format = "[$git_branch$directory |](bold black) "

[git_branch]
format = " "

[directory]
format = "$path"
truncation_length = 2
truncation_symbol = "…/"
